<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>timer-icon.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64;ARM32</Platforms>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Languages\cs-cz.json" />
    <None Remove="Languages\de-de.json" />
    <None Remove="Languages\el-gr.json" />
    <None Remove="Languages\en-gb.json" />
    <None Remove="Languages\ja-jp.json" />
    <None Remove="Languages\sd-sd.json" />
    <None Remove="Languages\zh-cn.json" />
    <None Remove="MyApps.xml" />
    <None Remove="Resources\chart-icon1.png" />
    <None Remove="Resources\language-icon.png" />
    <None Remove="Resources\timer-icon1.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Languages\_sbr_credits_info.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="MyApps.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="timer-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Languages\en-gb.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\FrmPomodoro.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\UcStatistics.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Forms\UcAbout.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Forms\UcLanguage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Forms\UcSettings.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ResourcesFlagsDir\ResourcesFlags.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourcesFlags.resx</DependentUpon>
    </Compile>
    <Compile Update="ResourcesIconsDir\ResourcesIcons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourcesIcons.resx</DependentUpon>
    </Compile>
    <Compile Update="ResourcesMyApps\ResourcesMyApps.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourcesMyApps.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="ResourcesFlagsDir\ResourcesFlags.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourcesFlags.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ResourcesIconsDir\ResourcesIcons.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourcesIcons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ResourcesMyApps\ResourcesMyApps.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourcesMyApps.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Sounds\sound1.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound3.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
   </ItemGroup>

</Project>