//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBR.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBR.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        internal static string Add_new_task {
            get {
                return ResourceManager.GetString("Add new task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1 time [min]:.
        /// </summary>
        internal static string Alarm_1_time__min__ {
            get {
                return ResourceManager.GetString("Alarm 1 time [min]:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 2 time [min]:.
        /// </summary>
        internal static string Alarm_2_time__min__ {
            get {
                return ResourceManager.GetString("Alarm 2 time [min]:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 3 time [min]:.
        /// </summary>
        internal static string Alarm_3_time__min__ {
            get {
                return ResourceManager.GetString("Alarm 3 time [min]:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 4 time [min]:.
        /// </summary>
        internal static string Alarm_4_time__min__ {
            get {
                return ResourceManager.GetString("Alarm 4 time [min]:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application which is tracking time you are using your computer and is reminding you to take a break.This application is free for any personal or commercial use..
        /// </summary>
        internal static string An_application_which_is_tracking_time_you_are_using_your_computer_and_is_reminding_you_to_take_a_break_This_application_is_free_for_any_personal_or_commercial_use_ {
            get {
                return ResourceManager.GetString("An application which is tracking time you are using your computer and is remindin" +
                        "g you to take a break.This application is free for any personal or commercial us" +
                        "e.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive task.
        /// </summary>
        internal static string Archive_task {
            get {
                return ResourceManager.GetString("Archive task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived tasks:.
        /// </summary>
        internal static string Archived_tasks_ {
            get {
                return ResourceManager.GetString("Archived tasks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average stats:.
        /// </summary>
        internal static string Average_stats_ {
            get {
                return ResourceManager.GetString("Average stats:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break NO.
        /// </summary>
        internal static string Break_NO {
            get {
                return ResourceManager.GetString("Break NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break YES.
        /// </summary>
        internal static string Break_YES {
            get {
                return ResourceManager.GetString("Break YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check also these free apps:.
        /// </summary>
        internal static string Check_also_these_free_apps_ {
            get {
                return ResourceManager.GetString("Check also these free apps:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:.
        /// </summary>
        internal static string Credits_ {
            get {
                return ResourceManager.GetString("Credits:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom colour.
        /// </summary>
        internal static string Custom_colour {
            get {
                return ResourceManager.GetString("Custom colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily averages for the last 10 days. Except today..
        /// </summary>
        internal static string Daily_averages_for_the_last_10_days__Except_today_ {
            get {
                return ResourceManager.GetString("Daily averages for the last 10 days. Except today.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily averages for the last 14 months:.
        /// </summary>
        internal static string Daily_averages_for_the_last_14_months_ {
            get {
                return ResourceManager.GetString("Daily averages for the last 14 months:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day/days.
        /// </summary>
        internal static string day_days {
            get {
                return ResourceManager.GetString("day/days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days before due date..
        /// </summary>
        internal static string days_before_due_date_ {
            get {
                return ResourceManager.GetString("days before due date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string Due_date {
            get {
                return ResourceManager.GetString("Due date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date:.
        /// </summary>
        internal static string Due_date_ {
            get {
                return ResourceManager.GetString("Due date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task.
        /// </summary>
        internal static string Edit_task {
            get {
                return ResourceManager.GetString("Edit task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoticons :) (:.
        /// </summary>
        internal static string Emoticons______ {
            get {
                return ResourceManager.GetString("Emoticons :) (:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra alert for long break.
        /// </summary>
        internal static string Extra_alert_for_long_break {
            get {
                return ResourceManager.GetString("Extra alert for long break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish task.
        /// </summary>
        internal static string Finish_task {
            get {
                return ResourceManager.GetString("Finish task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information about this app please check online help page:.
        /// </summary>
        internal static string For_more_information_about_this_app_please_check_online_help_page_ {
            get {
                return ResourceManager.GetString("For more information about this app please check online help page:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide priority, tag and status column..
        /// </summary>
        internal static string Hide_priority__tag_and_status_column_ {
            get {
                return ResourceManager.GetString("Hide priority, tag and status column.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons/flags:.
        /// </summary>
        internal static string Icons_flags_ {
            get {
                return ResourceManager.GetString("Icons/flags:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle time.
        /// </summary>
        internal static string Idle_time {
            get {
                return ResourceManager.GetString("Idle time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored breaks.
        /// </summary>
        internal static string Ignored_breaks {
            get {
                return ResourceManager.GetString("Ignored breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored breaks [-].
        /// </summary>
        internal static string Ignored_breaks____ {
            get {
                return ResourceManager.GetString("Ignored breaks [-]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month/months.
        /// </summary>
        internal static string month_months {
            get {
                return ResourceManager.GetString("month/months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string Note_ {
            get {
                return ResourceManager.GetString("Note:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        internal static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro 4/4.
        /// </summary>
        internal static string Pomodoro_4_4 {
            get {
                return ResourceManager.GetString("Pomodoro 4/4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro 4/4. Take a long break..
        /// </summary>
        internal static string Pomodoro_4_4__Take_a_long_break_ {
            get {
                return ResourceManager.GetString("Pomodoro 4/4. Take a long break.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string Priority_ {
            get {
                return ResourceManager.GetString("Priority:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random colour.
        /// </summary>
        internal static string Random_colour {
            get {
                return ResourceManager.GetString("Random colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        internal static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring task:.
        /// </summary>
        internal static string Recurring_task_ {
            get {
                return ResourceManager.GetString("Recurring task:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring tasks:.
        /// </summary>
        internal static string Recurring_tasks_ {
            get {
                return ResourceManager.GetString("Recurring tasks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind.
        /// </summary>
        internal static string Remind {
            get {
                return ResourceManager.GetString("Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen task.
        /// </summary>
        internal static string Reopen_task {
            get {
                return ResourceManager.GetString("Reopen task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        internal static string Repeat_every {
            get {
                return ResourceManager.GetString("Repeat every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset alarm.
        /// </summary>
        internal static string Reset_alarm {
            get {
                return ResourceManager.GetString("Reset alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        internal static string Run_at_startup {
            get {
                return ResourceManager.GetString("Run at startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        internal static string Select_your_language_ {
            get {
                return ResourceManager.GetString("Select your language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tasks:.
        /// </summary>
        internal static string Show_tasks_ {
            get {
                return ResourceManager.GetString("Show tasks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound alarm.
        /// </summary>
        internal static string Sound_alarm {
            get {
                return ResourceManager.GetString("Sound alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds:.
        /// </summary>
        internal static string Sounds_ {
            get {
                return ResourceManager.GetString("Sounds:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status_ {
            get {
                return ResourceManager.GetString("Status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        internal static string Tag_ {
            get {
                return ResourceManager.GetString("Tag:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks:.
        /// </summary>
        internal static string Tasks_ {
            get {
                return ResourceManager.GetString("Tasks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s stats:.
        /// </summary>
        internal static string Today_s_stats_ {
            get {
                return ResourceManager.GetString("Today\'s stats:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        internal static string ToDo {
            get {
                return ResourceManager.GetString("ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string Total_time {
            get {
                return ResourceManager.GetString("Total time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week/weeks.
        /// </summary>
        internal static string week_weeks {
            get {
                return ResourceManager.GetString("week/weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time.
        /// </summary>
        internal static string Working_time {
            get {
                return ResourceManager.GetString("Working time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time, total time [hours].
        /// </summary>
        internal static string Working_time__total_time__hours_ {
            get {
                return ResourceManager.GetString("Working time, total time [hours]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
